<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1XdJBw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1XdJBw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL1XdJBw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL1XdJBw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL1XdJBw\App_KernelDevDebugContainer([
    'container.build_hash' => 'L1XdJBw',
    'container.build_id' => '6fd17c43',
    'container.build_time' => 1712910007,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1XdJBw');
