<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfxL3Mw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfxL3Mw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAfxL3Mw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAfxL3Mw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAfxL3Mw\App_KernelDevDebugContainer([
    'container.build_hash' => 'AfxL3Mw',
    'container.build_id' => '831b390c',
    'container.build_time' => 1712923247,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAfxL3Mw');
